Addition of 5 minute timeout for ticket assign, fixed zendesk ticket bug
teknofire/chef-support-bot pull request #5
Opened 2018-07-19 20:37 UTC by glasschef

2018-07-20 21:27 UTC, teknofire requested changes

2018-07-20 21:27 UTC, teknofire commented on app/controllers/api/slack_controller.rb
> +      ProcessInteractiveMessageJob.perform_now(payload.as_json)
Any reason for changing this from `perform_later` to `perform_now`? The `perform_now` will skip queueing the job to the sucker punch worker and run it in the current web request instead.

2018-07-20 21:27 UTC, teknofire commented on app/controllers/api/slack_controller.rb
> +      ProcessSlackMessageJob.perform_async(event_params.as_json)
This should be left as `perform_later`, that's the method provided by ActiveJob and will call out to the `perform_async` in the ActiveJob sucker punch adapter.

2018-07-20 21:27 UTC, teknofire commented on app/jobs/process_slack_message_job.rb
> +  workers 20
Looking through how this is handled it appears that it needs to do this using an initializer in rails because of the way it SuckerPunch adapter wraps the actual job class created.

```
# config/initializers/sucker_punch.rb
ActiveJob::QueueAdapters::SuckerPunchAdapter::JobWrapper.workers 1
```

2018-07-20 21:27 UTC, teknofire commented on app/jobs/process_slack_message_job.rb
> +  def message_keyword(text)
The `message_keyword`,  `bot_match`, and `find_person` methods are no longer needed here, I moved the handling for this to the MySlack::Command class

2018-07-23 18:59 UTC, glasschef commented
closing in favor of incoming PR

2018-07-23 18:59 UTC, closed without merging